In [5]:
#0. 작업준비
import numpy as np
import pandas as pd

In [11]:
#1.데이터 수집
data_set=[[270,'울퉁불퉁','오렌지'],[250,'울퉁불퉁','오렌지'],[220,'매끈','사과'],[240,'매끈','사과']]
df=pd.DataFrame(data=data_set,columns=['무게','표면상태','결과'])
df

    무게  표면상태   결과
0  270  울퉁불퉁  오렌지
1  250  울퉁불퉁  오렌지
2  220    매끈   사과
3  240    매끈   사과

In [13]:
#2.데이터 분석 및 준비

#데이터 인스턴스 4개 있다 
#데이터는 2개의 특징을 갖는다 
#데이터는 2종의 정답을 갖는다 

#데이터 이슈
#1. 결측치
#2. 이상치 
#3. 컴퓨터가 이해할수없는 데이터
#4. 특징의 편차

#컴퓨터가 이해할수있는 내용으로 전달 해야 한다.
df

    무게  표면상태   결과
0  270  울퉁불퉁  오렌지
1  250  울퉁불퉁  오렌지
2  220    매끈   사과
3  240    매끈   사과

In [17]:
#데이터 이슈 3 해결
data_set=[[270,0,0],[250,0,0],[220,1,1],[240,1,1]]
df=pd.DataFrame(data=data_set,columns=['무게','표면상태','결과'])
df

    무게  표면상태  결과
0  270     0   0
1  250     0   0
2  220     1   1
3  240     1   1

In [31]:
X=df.drop('결과',axis=1).to_numpy()
y=df.drop(['무게',	'표면상태'],axis=1).to_numpy()

In [45]:
#3.학습
from sklearn.tree import DecisionTreeClassifier
m=DecisionTreeClassifier()
m.fit(X,y)

DecisionTreeClassifier()

In [49]:
#4. 예측 및 검증
m.score(X,y)

1.0

In [53]:
#5. 모델 사용 예측
def 과일_판별기(x1,x2):
    모델_입력데이터=[]
    입력데이터=[x1,x2]
    모델_입력데이터.append(입력데이터)
    결과_집합=m.predict(모델_입력데이터)
    결과=결과_집합[0]
    정답=['오렌지','사과']
    return 정답[결과]
과일_판별기(220,1)

'사과'