# 제어문
1. 조건문
   - if 조건
         - 단독 사용가능
         - 여려개 사용 가능
   - else(나머지)
         - 반드시 윗블록에 조건블록이 있어야 한다.
   - elif(나머지중 조건)
         - else if 의 준말
         - 아닌것들 중 조건
         - else블록안에서 if 를 선언한것과 유사
     
2. 반복문
    - for
       - 조건기반의 반복문 
       - 횟수기반의 반복문
       - 차원 내리기 또는 원소 추출
    - while
       - 조건기반의 반복문

In [ ]:
변수 in [변수집합] 관계연산자 중 in 연산자
원소 in [집합] #원소 확인 관계연산자

In [ ]:
is #동일 객체 확인
in #원소 포함확인
== #동일 값 확인

In [4]:
a=10
b=10
a == b,a is b

(True, True)

In [6]:
#is
id(a)==id(b)

True

In [10]:
a_l=[1,2,3,4]
b_l=[1,2,3,4]
a_l==b_l, a_l is b_l

(True, False)

In [12]:
#is
id(a_l)==id(b_l)

False

In [14]:
#조건
for 1 in a_l:
    pass
else:
    print("프로그램 동작후 자원정리")
while True:
    pass
else:
    print("프로그램 동작후 자원정리")

True

# 블록(실행/제어)
- 들여쓰기로 판단
- 일반적인 블록은 전부다 실행블록이다.
- 제어블록은 반복문블록 이다.
- 실행블록은 무조건 위에서 아래로 진행된다.
- 제어블록은 위로도 이동이 가능하다.

In [19]:
for 변수 in range(5):
    print(변수)

0
1
2
3
4

In [ ]:
range(5)#집합구조

In [ ]:
range(시작값=0,종료조건,증감식=1)

In [23]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
list(range(10,0,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [27]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
[0 for _ in range(10)]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [31]:
[0]*10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [37]:
a=[[0,0,0,0,0]]*5
a[0][0]=10
a

[[10, 0, 0, 0, 0],
 [10, 0, 0, 0, 0],
 [10, 0, 0, 0, 0],
 [10, 0, 0, 0, 0],
 [10, 0, 0, 0, 0]]

In [39]:
b=[[0 for _ in range(5)] for _ in range(5)]
b[0][0]=10
b

[[10, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

Q 학점계산기를 만들어 주세요
- 1. 1회 동작
- 2. 10점범위로 학점을 구분해 주세요
- 3. 0~100점의 점수 범위만 적용된다. 범위 벗어나면 <범위를 벗어났습니다.>를 출력 하시오
- 4. (A,B,C,D)는 10범위 ,F는 나머지
- 5. 점수를 직접 입력 할 수 있어야 합니다.

# 리스트 1:1관계
- 여러개의 데이터를 저장하기위해서 만들 구조
- 하나의 이름으로 여러개의 값을 받기위한 구조
- 차원
    - 차원구조에 여러개의 값을 넣더라도 하나의 값을 이야기한다.(이름은 1개 만들면 된다.)
    - 단/다 차원 차원을 형상
        - 축이 있다.
            - 축이 1개다
            - 축이 여러개다
- 인덱스(상대주소)<0~>
    - 양수
        - 데이터의 시작 지점부터 데이터접근
        - 0~ 
    - 음수
        - 데이터의 끝지점 부터 데이터 접근
        - -1~
    - 순서를 가지고있다.
    - 인덱싱
        - 차원 내리기 
    - 슬라이싱
        - 차원 유지
리스트 이름[고차원][저차원]

In [47]:
a=[1,2,3,4,5]#1차원 데이터
a[-3]

3

In [50]:
#인덱싱 - 차원 내리기
a[0]#인덱싱

1

In [52]:
b=[[1,2,3]]
b[0]

[1, 2, 3]

In [13]:
#슬라이싱-> 새로 만들기
#[시작인덱스:종료인덱스:방향=1]

In [5]:
l=[1,2,3,4,5]
l[0:1:1]

[1]

In [9]:
l[1:0:-1]

[2]

In [11]:
l[::-1]

[5, 4, 3, 2, 1]

In [15]:
b=l

In [21]:
id(b),id(l),b==l,b is l

(2557323871040, 2557323871040, True, True)

In [23]:
b=l[:]
id(b),id(l),b==l,b is l

(2555707125120, 2557323871040, True, False)

In [ ]:
b[시작 인덱스:종료 인덱스: 방향값]

In [33]:
l[1::-2]

[2]

In [35]:
l=[1,2,3]

In [39]:
l[0]#l의 주소에서 0번 움직여서 그장소의 공간에 데이터를 줘

1

In [41]:
l[2]#l의 주소에서 2번 움직여서 그장소의 공간에 데이터를 줘

3

In [43]:
l[3]#l의 주소에서 3번 움직여서 그장소의 공간에 데이터를 줘

IndexError: list index out of range

In [53]:
l=[1,2,3]
l

[1, 2, 3]

In [55]:
l.insert(0,100)#0번 위치에 공간을 밀어 넣어줘
l

[100, 1, 2, 3]

In [ ]:
l[0]=10#0번 위치의 공간에 값을 바꿔줘

In [45]:
l.insert()

TypeError: insert expected 2 arguments, got 0

l.insert(100,100)
l

인덱스(상대적주소)<br>
판다스의 인덱스(값)

In [81]:
import pandas as pd
k=pd.DataFrame({'a':[1,1,1,1],'b':[2,2,2,2],'c':[3,3,3,3]},index=[1,2,1,4])
k

   a  b  c
1  1  2  3
2  1  2  3
1  1  2  3
4  1  2  3

In [95]:
d={1:100,2:200}
d[1]

100

In [89]:
k.loc[1]#일반적으로 테이블 구조를 읽는 방식으로 전환

   a  b  c
1  1  2  3
1  1  2  3

In [91]:
k.iloc[1]#상대적 주소로 바꿔라

a    1
b    2
c    3
Name: 2, dtype: int64